export const productos = [
    {
        id: 1,
        nombre: "Celular S10",
        descripcion: "4G LTE, 128GB",
        marca: "Samsung",
        categoria: "Smartphone",
        precioARS: 150000,
        precioUSD: 13500,
        stock: 5,
        img : "",
    },
    {
        id: 2,
        nombre: "Notebook A3",
        descripcion: "16 pulgadas con M1",
        marca: "Apple",
        categoria: "Laptop",
        precioARS: 300000,
        precioUSD: 27000,
        stock: 2,
        img : "",
    },
    {
        id: 3,
        nombre: "Auriculares",
        descripcion: "Auriculares bluetooth",
        marca: "Sony",
        categoria: "Auriculares",
        precioARS: 50000,
        precioUSD: 4500,
        stock: 7,
        img : "",
    },
    {
        id: 4,
        nombre: "Televisor 4K",
        descripcion: "SmarTV LG 4K 43 pulgadas",
        marca: "LG",
        categoria: "SmartTV",
        precioARS: 200000,
        precioUSD: 18000,
        stock: 2,
        img : "",
    },
    {
        id: 5,
        nombre: "Televisor 8K",
        descripcion: "smartTV 8K 55 pulgadas, HDR",
        marca: "Samsung",
        categoria: "SmartTV",
        precioARS: 250000,
        precioUSD: 22500,
        stock: 3,
        img : "",
    },
    {
        id: 6,
        nombre: "Celular 13",
        descripcion: "4G LTE, 64GB",
        marca: "Apple",
        categoria: "Smartphone",
        precioARS: 130000,
        precioUSD: 11000,
        stock: 4,
        img : "",
    },
    {
        id: 7,
        nombre: "Notebook VAIO",
        descripcion: "14 pulgadas, ryzen 7, 32 gb RAM",
        marca: "Sony",
        categoria: "Laptop",
        precioARS: 250000,
        precioUSD: 22500,
        stock: 5,
        img : "",
    },
    {
        id: 8,
        nombre: "Auriculares BT",
        descripcion: "Auriculares bluetooth, cancelacion de ruido",
        marca: "LG",
        categoria: "Auriculares",
        precioARS: 40000,
        precioUSD: 37000,
        stock: 9,
        img : "",
    },
    {
        id: 9,
        nombre: "Notebook galaxy",
        descripcion: "ryzen 5, 16GB RAM",
        marca: "Samsung",
        categoria: "Laptop",
        precioARS: 150000,
        precioUSD: 13500,
        stock: 5,
        img : "",
    },
    {
        id: 10,
        nombre: "Tablet ipad",
        descripcion: "ryzen 7, 16GB RAM",
        marca: "Apple",
        categoria: "Tablet",
        precioARS: 300000,
        precioUSD: 27000,
        stock: 2,
        img : "",
    },
    {
        id: 11,
        nombre: "Celular Xperia",
        descripcion: "5G LTE, 128GB",
        marca: "Sony",
        categoria: "Smartphone",
        precioARS: 50000,
        precioUSD: 4500,
        stock: 7,
        img : "",
    },
    {
        id: 12,
        nombre: "Televisror UHD",
        descripcion: "43 pulgadas, UHD",
        marca: "Noblex",
        categoria: "SmartTV",
        precioARS: 200000,
        precioUSD: 18000,
        stock: 2,
        img : "",
    },
    {
        id: 13,
        nombre: "Aire acondicionado inverter",
        descripcion: "Frio/calor, 3500w ",
        marca: "Samsung",
        categoria: "Split",
        precioARS: 250000,
        precioUSD: 22500,
        stock: 3,
        img : "",
    },
    {
        id: 14,
        nombre: "Airo acondicionado",
        descripcion: "Frio 2500w",
        marca: "Noblex",
        categoria: "Split",
        precioARS: 130000,
        precioUSD: 11000,
        stock: 4,
        img : "",
    },
    {
        id: 15,
        nombre: "Televisor",
        descripcion: "55 pulgadas, 4K HDR",
        marca: "Sony",
        categoria: "SmartTV",
        precioARS: 250000,
        precioUSD: 22500,
        stock: 5,
        img : "",
    },
    {
        id: 16,
        nombre: "Aire acondicionado inverter",
        descripcion: "Frio/calor 4000w",
        marca: "LG",
        categoria: "Split",
        precioARS: 40000,
        precioUSD: 37000,
        stock: 9,
        img : "",
    }
];